name: Docker Image CI
on:
  push:
    branches: [ "main" ]
jobs:
  push-bot:
    runs-on: ubuntu-latest
    environment: docker-images-ci-actions-env
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build . -t "${{ vars.DOCKERHUB_USERNAME }}/ru-ege-telegram-bot:latest"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      - name: Push to Docker Hub
        run: docker push "${{ vars.DOCKERHUB_USERNAME }}/ru-ege-telegram-bot:latest"
